### ISSUE TITLE
Error if # of peaks to output is zero

### ISSUE THREAD

**Issue by snopeusz** [v7b1/fiddle_64bit_version#1]
[Max 7.2.2-64bit/MacOS 10.11.4]
if 'number to peaks to output' argument is zero (default) object isn't created and the error message is posted: "fiddle~: out of memory".

**Comment by v7b1** [comment]
should be fixed now, thanks!

**Comment by snopeusz** [comment]
thank you! I don't have dev tools on my machine – could you put compiled external online? TIA:)

**Comment by v7b1** [comment]
ok, updated the .zip file in the current release with a newly compiled osx version. windows will have to wait until someone else, e.g. simone, does it.
