### ISSUE TITLE
Higher CPU usage when auto set to 0

### ISSUE THREAD

**Issue by snopeusz** [v7b1/fiddle_64bit_version#2]
"auto 0": fiddle~ doesn't send anything, but DSP CPU usage increases by 30%.

<pre><code>
----------begin_max5_patcher----------
2255.3oc6c9rbiZrEGds8SQWTYQtU4Lo+GzzIqRcWc2kMYUlTovRHaRIAJ.J
imjJSceGtu.2mk7njmjveUriAwuXF2Ap5rwZLFAm9b93.eBQO+x0W4ca1CwE
druf8srqt5Wt9pqZVT8Btp62ux6PzCa1GUzrZdaxNbHNsz6l1+VY7CkMKWye
fsKY618wef8Yr2ce19XVQYdR5crh3MkIYoru7e0+tROcHIcebYylTzsvhx2u
OtYa8nUK6TY+5w6V5wnxM2Wsc+97psaanqBLugeCKzvqeQXCpeQV8Kruq6Mk
rsYKmc6O7YBQfW8B+0qut9G2.NvSieW069Yi6hn28AlOmO3PSBNzDiOzz90i
kflAVfrYbIGabo625sa5x2eLtci3UjbWZzdO128BF3iUwKOkmVWdeqWzoxr2
5wx1sikjtIONpHtf8u+5ugcpH5tX1sumI9b0aS+Or3GNVMvh2xpxQIGh12rR
u693TVZFaaTYDKonBWRKYeZT5VVxNVQF62+u+ue6+Wdebdb8esZESiq1B6xx
YUQ1wSkQ0v0YzZeRZ7lrSoMwn5Uh2zsDVEtICTVsopn3aqWh1LVsQ8Qj4xY6
1tePfiOefKvnaFasvlRbIjKPLJw4cd8OlGWWRaJSOY+D7n8Cu6GuHBcjzTe6
HAWpYJlkW8u5WocYokoQGZyQeUdRz9+l8l1jsOKucjHZiciPYjh5+kPozgxa
p+CmyBOM+alN+aa.Jgr4EoZjBfbzBvt8YQUGzx7tMJ8t5W2mTTNzqmWwlEbd
uTmgJR94lMmnZ2iUMai5WipoKf9.qA.5UyF561ODz+WgdkFA58WXPeaTuZgd
ERm9f4C8JpS+f4+.nN8lkEz2E0qUn2O.oSe3rg9t8CA8+UnmC0o2tvfd9ptS
uOGnSugOenmSc5GL+qP5zaDKKnuKpWcPue60a.IxZjubn2WoIQ1Kj+gDYMpE
Bz2WMsqZnGRj0nmMzShri.8PhrF+EFzuREY6gdDQVSv7gdRjc37OjHqwrrf9
0pHaWRGRj0DNanmDYGA5gDYM1EFzyW0c5gDYC4yG5IQ1gy+PhrghkEzuVEYU
VNrHa3LDYUVIIxdg7OjHa3RQjsuZZW0POjHand1POIxNBzCIxF5uvf9UpHaO
ziHxFFLenmDYGN+CIxFZVVP+ZUjsKoCIxFFNanmDYGA5gDYCsKLnmup6zCIx
Z4yG5IQ1gy+PhrVwxB5WqhrRcHrHqcFhrReNIxdg7OjHqcoHx1WMsqZnGRj0
pmMzShri.8PhrV+EFzuREY6gdDQVav7gdRjc37OjHq0rrf90pHaWRGRj0FNa
nmDYGA5gDYs1EFzyW0c5gDYEb97odxjc3B.jIqfKVVX+ZUkUvCfUYq3oWN1K
3gjK6EJ.VLreoHy1WNsqZrGRlUv0yF6Ia1QvdHaVA2egg8qTc1drWA0sOX9X
O4yNbAH.qauYYg8qUg1trNjPa0Pc1XOYzNB1yw51aWXXOeU2sGSoUvmO1SJs
CW.vTZEhkE1+Jpz9iGhKyyXhWuoaLkeCKpCeie0kqc4YGgwI+lz8KZfWUHph
0WHhVlmTrIpcnyeiczrQ05UEfcq2fYH4jYHgj+Fow2Wnpp3lmAn6xxOD07NB
ddly+70mbLJuZ3UFm+8woQ29zH548St4blcD97iGoEssnhuOUv1b7zeypAJE
NcNNTdd9UKTeod.9ielu5jVRZoKxYaKNVmzh+vrllC0SlVjc2yqKcvo+3RH0
YiG2xq62aSRqqIzBMhPl9h9XzTSQalDxrR6Nwp0EHpPTjzgDHNMHB45nsDHN
LHhHs3yIPb5LIj8guf.wASeREPGQeIAhSmIMHcD8UDHNX5SXP5HpIPbZPjC0
Qzm.wAen4gjUTjrxzS+.XxJJRVY3zGjrhhjU..QHYEEIqLBHhHqnIYkoAQLY
EMIqLb5CRVQSxJSChXxJZRVY3zGjrhljU..QHYEMIqL7CFMjrhjjUl9QLGSV
QRxJCm9fjUjjrB.HBIqHIYkQ.QDYEEIqLMHhIqnHYkgSePxJJRVYZPDSVQQx
JCm9fjUTjrB.HBIqnHYkge1WgjUDjrxzOEwXxJBRVY3zGjrhfjU..QrG4ERV
YDPDQVQRxJSChXxJRRVY3zGjrhjjUlFDwjUjjrxvoOHYEIIq..hPxJRRVY3m
pQLYEBDm94CETVg.wgSeXxJzolA.QLYE5Tyi.hXycbDHNclD7Ilm.wASePxJ
zmdyzbHlqxh9CuoL6t5YHf47jbOMvIZIMc+OG7+5HeQyU.u3ml6CwEEQ2E+7
IDfSkYrOQ7ZMuSb9hialAMt7ypiaN.rXzFNn0e9z0+911W7Nn4st5hhYZ+Qt
HF+yai17gYQmWnbIM8mXvuhQ8aHU+QN4pGcNf.7Olf.8+DmDnYcpV8z3h1cV
eYpY3Tu7mVrJxNkuoOtZuDpp3l8minswEkIoMSHPOZsTOYctupZFm9XRaaRQ
ci7lrwvmiBOd3.wSyTkjqhn54Ctoin54rLmEQAPQjwgQjFJh7cXDIghH2Q1V
j.x5v3AojYcWEyh.0V2wzVjC6st7ndnNib20YzhDPV2EOgHUrP2UwBQH5P2Q
zgHGwG5ti3CQ5HF5tNhFj3w3v3AodYbW8xfvyF2wyFji2MN73cj9ggtqenAI
dLtKdBPpWAtqdEfvyAtimCTHwi6NdOPfDOR2EOH7ru63GeH9g6t3whjebGOq
QxOZGFOH8ezNjef3Y20e1G45e7c20+3ib8O9tqenFIdzNLdPpWZ2UuzH7r1c
7rB43ck6NdWgzOT4t9gRj3Q5v3AodIcX8BgmUNjmQNdW4ti2UP25.20OThDO
RGFOH0Ko6pWRDdV5v6rBzMVwgeBqP2VEGdWUftoJN7dp.cKUb38JD6VE5tO+
GjONb2czNhbp1ceXTHWKu6TKdEuo2s2S9niG+o37htMYSf3cH5GZ+lJz7kNv
6PRZ6u17E6vKO9mR5W+1kDku49jx3Mkmxa+JO7P22x.uCYaiySOkz7UB3558
7ud8e..SDmEL
-----------end_max5_patcher-----------
</code></pre>

**Comment by v7b1** [comment]
sorry, can't confirm that. cpu usage stays exactly the same on my machine (osx10.8.5, Max6.1.10).
and this is expected behaviour.
"auto 0" only switches off the automatic outlet calls, but not the internal analysis. to save cycles it might be a good extension to also stop the internal analysis, but right now it is like Miller designed it and will not change any time soon.

**Comment by snopeusz** [comment]
thank you for looking into this. I'll try to confirm if this is an issue with Max7 (I have an access to machine with installed both Max6 and Max7) in a few days.
